### ISSUE TITLE
Full config options for 1.12.2

### ISSUE THREAD

**Issue by AtzG5O8** [henkelmax/corpse#5]
Hello there,

Is there any chance that you'd be planning on or able to (easily) implement the full configuration options for the 1.12.2 version. The options we (my server players) were hoping for were particularly the delay on being able to loot the skeleton of another player and the time it takes for a corpse to become a skeleton.

I was also wondering, apart from this, in the 1.12.2 version of the mod in the .cfg, what time value does the line "I:force_despawn_time" refer to? Is it represented in seconds, minutes? Just wondering so I can add a good value to clean up corpses but still give players a chance to retrieve their items.

Thanks so much and I hope you have a great day! How is the weather in Germany? :) 🇩🇪 

Atz

**Comment by henkelmax** [comment]
Hi,
Unfortunately I can only maintain the last two major versions. I usually add new features only to the latest version (depends on the complexity and differences between these versions).
Maintaining all versions down to 1.12 would mean maintaining 5 versions of all my 13 mods. This would take me way to much time that I could otherwise put into new features, bugfixes and new mods.

> I was also wondering, apart from this, in the 1.12.2 version of the mod in the .cfg, what time value does the line "I:force_despawn_time" refer to? Is it represented in seconds, minutes? Just wondering so I can add a good value to clean up corpses but still give players a chance to retrieve their items.

The despawn time is in ticks (20 ticks = 1 second).

> Thanks so much and I hope you have a great day! How is the weather in Germany? :) 🇩🇪

Thank you! It is currently colder again, a pleasant change to the hot weather.

If you have any other questions feel free to ask.

Greetings henkelmax
