### ISSUE TITLE
NBT data kick error

### ISSUE THREAD

**Issue by vERKE** [henkelmax/corpse#58]
**Bug description**
A friend of mine died, he got killed by a Gorgon, and got kicked from the server with this error message:
https://cdn.discordapp.com/attachments/797432284416180224/876169389676847114/unknown.png

**Steps to reproduce the issue**
1. Get killed by the Gorgon.
2. Get kicked with the error message.

**Expected behavior**
Not to get kicked

**Log files**
Log files here: [https://pastebin.com/F0wMisV3](https://pastebin.com/F0wMisV3).

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.2.2.
- Mod version: corpse-1.16.5-1.0.5.jar - Release

**Other mods**
Modlist, modpack download (private modpack for my friends): https://pastebin.com/888WV9kV

**Screenshots (Optional)**
https://cdn.discordapp.com/attachments/797432284416180224/876169389676847114/unknown.png

**Comment by henkelmax** [comment]
Can you also send me the logs of the client?

**Comment by vERKE** [comment]
I can't upload the server logs to Pastebin as it says I exceed the limit. I have uploaded them, and please take a look at them:
Server logs:
https://subirat.net/mc/latest.log
https://subirat.net/mc/debug.log
I will tell my friend to launch his Minecraft and try to join so I can send you the client-side logs too.

**Comment by vERKE** [comment]
Also, here is the client log:
https://pastebin.com/AHKBnuz7

**Comment by henkelmax** [comment]
I can't seem to find anything related to this kick message.

But this message usually occurs if some mod saves too much data to an item. This causes the packet that gets sent over the network when dying that contains the death items to be too big.
This is indirectly caused by another mod.
I would suggest finding the mod that creates items with too much NBT data.
