### ISSUE TITLE
Despawn inventory when corpse despawns

### ISSUE THREAD

**Issue by kreezxil** [henkelmax/corpse#60]
**Is your feature request related to a problem? Please describe.**
I want the contents of the items to vanish if the corpse is not looted by the time it despawns.

**Describe the solution you'd like**
Need a config option to turn on despawning items when the corpse despawns.

**Describe alternatives you've considered**
have not considered anything else

**Additional context**
on version: 1.16.5-1.0.6

**Comment by KRCentury** [comment]
![Screenshot_28](https://user-images.githubusercontent.com/93412079/139513045-8aad7186-8546-4365-9ccb-3fa9c1a79a80.png)

Describe the solution you'd like: NBT Issue caused by being turned to stone by Gorgon from Ice and Fire mod, hoping if it possible for a fix/patch to this as this occurs only when I approach the area where my body would be which is in the Gorgon Temple. 

Additional context: 1.16.5 Forge 36.2.8 

Describe alternatives you've considered: This has occured in a multiplayer server with a temporary solution of tping away before the crash occurs but doesn't get me my items I have lost back and leaves a corrupted area of the world where anyone else walks to it they will have the same crash/error.

**Comment by henkelmax** [comment]
Just wait 5 minutes and it will despawn. This is vanilla minecraft.

**Comment by henkelmax** [comment]
The mod is not intended to have corpses despawn anyways. Just don't set the despawn time and items won't get dropped.

**Comment by kreezxil** [comment]
But you have a config that allows them to despawn, they deteriorate over
time. That why I thought it might be good to suggest not allowing the items
to spew everywhere. I'll stop bothering you. This was supposed to be a
feature request not a bug report, and it was never an attack on your code.
